#!/usr/bin/env python3
"""Generate Builder hub Markdown indexes."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

LIB = Path(__file__).resolve().parents[3] / "lib"
sys.path.insert(0, str(LIB))

from artifact_quality import project_of
from builder_hub import extract_status, first_heading, list_markdown, parse_dated_file, read_text, write_text
from project_memory import PROJECT_LINE_RE


INDEX_TARGETS = {
    "docs/implementation-plans": "Implementation Plans",
    "docs/test-reports": "Test Reports",
    "docs/session-memory": "Session Memory",
}

MEMORY_DIRECTORY = "docs/session-memory"
# Plans and reports written before the Project section existed are listed under this heading, last.
UNLABELED_GROUP = "Before the Project field"


def item_line(index_file: Path, path: Path) -> str:
    parsed = parse_dated_file(path)
    date = parsed[0] if parsed else "project"
    title = first_heading(path)
    status = extract_status(read_text(path)) or ""
    link = path.name
    suffix = f" - `{status}`" if status else ""
    return f"- {date}: [{title}]({link}){suffix}"


def memory_day_line(path: Path) -> str:
    """One line per date, naming the projects whose entries the day holds."""
    projects = sorted({match.group("project") for match in PROJECT_LINE_RE.finditer(read_text(path))})
    suffix = f" - {', '.join(projects)}" if projects else ""
    return f"- [{path.stem}]({path.name}){suffix}"


def project_group_of(path: Path) -> str:
    """The project a plan or report belongs to, from its Project section."""
    return project_of(read_text(path)) or UNLABELED_GROUP


def build_index(root: Path, directory: str, title: str) -> tuple[Path, str]:
    target_dir = root / directory
    index_file = target_dir / "index.md"
    files = [path for path in list_markdown(root, directory) if path.name != "index.md"]
    if directory == MEMORY_DIRECTORY:
        lines = [f"# {title}", "", "Generated by `check_hub.py refresh`. One file per date.", ""]
        lines.extend(memory_day_line(path) for path in files)
        if not files:
            lines.append("No records yet.")
        return index_file, "\n".join(lines).rstrip() + "\n"
    lines = [f"# {title}", "", "Generated by `check_hub.py refresh`. Grouped by project.", ""]
    if not files:
        lines.append("No records yet.")
    files_by_project: dict[str, list[Path]] = {}
    for path in files:
        files_by_project.setdefault(project_group_of(path), []).append(path)
    ordered_projects = sorted(files_by_project, key=lambda project: (project == UNLABELED_GROUP, project))
    for project in ordered_projects:
        lines.extend([f"## {project}", ""])
        lines.extend(item_line(index_file, path) for path in files_by_project[project])
        lines.append("")
    return index_file, "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Builder hub index files.")
    parser.add_argument("--root", default=".")
    parser.add_argument("--check", action="store_true", help="Report stale indexes without writing.")
    args = parser.parse_args()
    root = Path(args.root).expanduser().resolve()

    outputs = list(
        build_index(root, directory, title)
        for directory, title in INDEX_TARGETS.items()
    )

    stale = []
    for path, content in outputs:
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing != content:
            stale.append(path)
            if not args.check:
                write_text(path, content)

    if args.check and stale:
        print("Stale or missing indexes:")
        for path in stale:
            print(path)
        return 1

    if stale:
        print("Updated indexes:")
        for path in stale:
            print(path)
    else:
        print("Hub indexes are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
