#!/usr/bin/env python3
"""Generate Builder hub Markdown indexes."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

LIB = Path(__file__).resolve().parents[3] / "lib"
sys.path.insert(0, str(LIB))

from builder_hub import extract_status, first_heading, list_markdown, parse_dated_file, read_text, write_text


INDEX_TARGETS = {
    "docs/work": "Work Records",
    "docs/spokes": "Spokes",
    "docs/decisions": "Decision Records",
    "docs/specs": "Project Specs",
    "docs/implementation-plans": "Implementation Plans",
    "docs/test-reports": "Test Reports",
    "docs/spoke-tasks": "Spoke Task Briefs",
    "docs/spoke-updates": "Spoke Updates",
    "docs/spoke-reviews": "Spoke Reviews",
    "docs/work-closures": "Work Closures",
    "docs/session-memory": "Session Memory",
}


def item_line(index_file: Path, path: Path) -> str:
    parsed = parse_dated_file(path)
    date = parsed[0] if parsed else "undated"
    title = first_heading(path)
    status = extract_status(read_text(path)) or ""
    link = path.name
    suffix = f" - `{status}`" if status else ""
    return f"- {date}: [{title}]({link}){suffix}"


def build_index(root: Path, directory: str, title: str) -> tuple[Path, str]:
    target_dir = root / directory
    index_file = target_dir / "index.md"
    files = [path for path in list_markdown(root, directory) if path.name != "index.md"]
    lines = [f"# {title}", "", "Generated by `update-hub-indexes`.", ""]
    if not files:
        lines.append("No records yet.")
    else:
        lines.extend(item_line(index_file, path) for path in files)
    return index_file, "\n".join(lines).rstrip() + "\n"


def build_active(root: Path) -> tuple[Path, str]:
    active_file = root / "docs" / "active.md"
    lines = ["# Active Hub Work", "", "Generated by `update-hub-indexes`.", ""]
    work_files = [path for path in list_markdown(root, "docs/work") if path.name != "index.md"]
    active = []
    for path in work_files:
        status = extract_status(read_text(path)) or "unknown"
        if status != "closed":
            active.append((path, status))
    if not active:
        lines.append("No active work records found.")
    else:
        for path, status in active:
            lines.append(f"- [{first_heading(path)}](work/{path.name}) - `{status}`")
    return active_file, "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Builder hub index files.")
    parser.add_argument("--root", default=".")
    parser.add_argument("--check", action="store_true", help="Report stale indexes without writing.")
    args = parser.parse_args()
    root = Path(args.root).expanduser().resolve()

    outputs = [build_active(root)]
    outputs.extend(build_index(root, directory, title) for directory, title in INDEX_TARGETS.items())

    stale = []
    for path, content in outputs:
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing != content:
            stale.append(path)
            if not args.check:
                write_text(path, content)

    if args.check and stale:
        print("Stale or missing indexes:")
        for path in stale:
            print(path)
        return 1

    if stale:
        print("Updated indexes:")
        for path in stale:
            print(path)
    else:
        print("Hub indexes are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
