#!/usr/bin/env python3
"""Generate Claude Code skill entrypoints that delegate to canonical .agents/skills."""
from __future__ import annotations

import argparse
from pathlib import Path
import re
import shutil
import sys

CANONICAL_DIR = Path(".agents/skills")
CLAUDE_DIR = Path(".claude/skills")
GENERATED_MARKER = "<!-- Generated by maintain-builder-hub from"
FRONTMATTER_RE = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)


def render_claude_skill(canonical_text: str, skill_name: str) -> str:
    frontmatter = FRONTMATTER_RE.match(canonical_text.replace("\r\n", "\n"))
    if not frontmatter:
        raise ValueError(f"{CANONICAL_DIR.as_posix()}/{skill_name}/SKILL.md: missing frontmatter")
    canonical = f"{CANONICAL_DIR.as_posix()}/{skill_name}/SKILL.md"
    return (
        f"{frontmatter.group(0)}\n"
        f"{GENERATED_MARKER} {canonical}; edit that file, then run maintain_builder_hub.py refresh. -->\n\n"
        f"# {skill_name}\n\n"
        f"Read and follow `{canonical}` from the Builder root. It is the canonical skill shared with Codex. "
        f"Resolve its relative links, `references/` and `scripts/` from `{CANONICAL_DIR.as_posix()}/{skill_name}/`, "
        f"and run its helper commands from the Builder root.\n"
    )


def expected_entrypoints(root: Path) -> dict[Path, str]:
    canonical_root = root / CANONICAL_DIR
    if not canonical_root.is_dir():
        return {}
    return {
        root / CLAUDE_DIR / skill.parent.name / "SKILL.md":
            render_claude_skill(skill.read_text(encoding="utf-8"), skill.parent.name)
        for skill in sorted(canonical_root.glob("*/SKILL.md"))
    }


def generated_entrypoints(root: Path) -> list[Path]:
    claude_root = root / CLAUDE_DIR
    if not claude_root.is_dir():
        return []
    return [path for path in sorted(claude_root.glob("*/SKILL.md"))
            if GENERATED_MARKER in path.read_text(encoding="utf-8")]


def find_drift(root: Path) -> list[str]:
    expected = expected_entrypoints(root)
    drift = [f"stale or missing: {path}" for path, content in expected.items()
             if not path.is_file() or path.read_text(encoding="utf-8").replace("\r\n", "\n") != content]
    drift += [f"orphaned: {path}" for path in generated_entrypoints(root) if path not in expected]
    return drift


def refresh(root: Path) -> list[Path]:
    expected = expected_entrypoints(root)
    for orphan in (path for path in generated_entrypoints(root) if path not in expected):
        shutil.rmtree(orphan.parent)
    written = []
    for path, content in expected.items():
        if not path.is_file() or path.read_text(encoding="utf-8").replace("\r\n", "\n") != content:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".")
    parser.add_argument("--check", action="store_true", help="Report drift without writing")
    args = parser.parse_args(argv)
    root = Path(args.root).expanduser().resolve()
    try:
        if args.check:
            drift = find_drift(root)
            for problem in drift:
                print(f"Claude skill entrypoint {problem}")
            return 1 if drift else 0
        for path in refresh(root):
            print(f"Updated Claude skill entrypoint: {path}")
        return 0
    except (ValueError, OSError) as error:
        print(str(error), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
